django/23.03.15/firsttpjt/firsttpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path("myapp2/", include('myapp2.urls')),

    # path("index/" , views.index),
    # path("profile/", views.profile),
    # path("fruits/", views.fruits),
    # path("template/", views.template),
    # path("hello/<name>/", v2.hello),
]

django/23.03.15/firsttpjt/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path("index/" , views.index, name="index"),
    path("profile/", views.profile, name="profile"),
    path("fruits/", views.fruits, name="fruits"),
    path("template/", views.template, name="template"),
]

django/23.03.15/firsttpjt/myapp2/urls.py
from django.urls import path
from . import views

app_name = 'myapp2'
urlpatterns = [
    path("hello/<name>/", views.hello, name = "hello")
]

django/23.03.15/firsttpjt/myapp2/models.py
from django.db import models

# Create your models here.

django/23.03.15/firsttpjt/myapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "myapp/index.html")


def profile(request):
    name = "jieun"
    age = 25

    info = {"name": name, "age": age}
    return render(request, "myapp/profile.html", info)

def fruits(request):
    f_list = ["apple" , "banana" , "melon"]
    context = {
        "fruits" : f_list
    }
    return render(request, "myapp/fruits.html", context)
    
def template(request):
    return render(request, "myapp/template.html")

django/23.03.15/firsttpjt/myapp2/views.py
from django.shortcuts import render

# Create your views here.
def hello(request, name):
    context = {'name': name}
    return render(request, "myapp2/hello.html", context)

django/23.03.15/firsttpjt/myapp/templates/myapp/fruits.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>MY FRUITS</h1>

    <ol>
      {% for fruit in fruits %}
        {% if fruit == "melon" %}
        <li>my favorite : {{fruit}}</li>
        {% else %}
        <li>{{fruit}}</li>
        {% endif %}
      {% endfor %}
    </ol>

    <p>{{fruits|length}}</p>
    <p>{{fruits|join:", "}}</p>
  </body>
</html>

django/23.03.15/firsttpjt/myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>INDEX PAGE</h1>

    <ul>
      <li>
        <a href="{% url 'myapp:profile' %}">profile</a>
      </li>
      <li>
        <a href="{% url 'myapp:fruits' %}">fruits</a>
      </li>
      <li>
        <a href="{% url 'myapp:template' %}">template</a>
      </li>
      <li>
        <a href="{% url 'myapp2:hello' 'jieun' %}">hello</a>
      </li>
    </ul>
  </body>
</html>

django/23.03.15/firsttpjt/myapp/templates/myapp/profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>PROFILE</h1>
    <ul>
      <li>name: {{name}}</li>
      <li>age: {{age}}</li>
    </ul>
  </body>
</html>

django/23.03.15/firsttpjt/myapp/templates/myapp/template.html
{% extends 'base.html' %}

{% block content1 %}
{% comment %} 1번 컨텐츠 블록에 들어갈 내용 {% endcomment %}
<button class="btn btn-primary">Primary</button>
{% endblock content1 %}

{% block content2 %}
{% comment %} 2번 컨텐츠 블록에 들어갈 내용 {% endcomment %}
<button class="btn btn-success">Success</button>
{% endblock content2 %}

django/23.03.15/firsttpjt/myapp2/templates/myapp2/hello.html
{% extends 'base.html' %}

{% block content1 %}
  <button class="btn btn-primary">{{ name }}</button>
{% endblock content1 %}

django/23.03.15/firsttpjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <title>Document</title>
  </head>
  <body>
    <h1>CONTENT1</h1>
    {% block content1 %}{% endblock content1 %}
    <h2>CONTENT2</h2>
    {% block content2 %}{% endblock content2 %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
      integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
      crossorigin="anonymous"
    ></script>
  </body>
</html>