django/23.03.20/day1_problem1/articles/urls.py
from django.urls import path
from . import views

app_name='articles'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('new/', views.new, name = 'new'),
    path('create/', views.create, name = 'create'),
]

django/23.03.20/day1_problem1/project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

django/23.03.20/day1_problem1/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django/23.03.20/day1_problem1/articles/views.py
from django.shortcuts import redirect, render
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article(title=title, content=content)
    article.save()
    return render(request, 'articles/create.html')

django/23.03.20/day1_problem1/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<h1 class="d-flex justify-content-center">성공적으로 글이 작성되었습니다.</h1>
<a href="{% url 'articles:index' %}">index</a>
{% endblock content %}

django/23.03.20/day1_problem1/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="d-flex justify-content-center">articles</h1>
  <a href="{% url 'articles:new' %}">new</a>
  <hr style="border: 1px black solid;">
  {% for article in articles %}
  
  <p>글 번호 : {{article.pk}} </p><br>
  <p>글 제목 : {{article.title}}</p><br>
  <p>글 내용 : {{article.content}}</p>
  <hr class="border-1">
    
  {% endfor %}
{% endblock %}

django/23.03.20/day1_problem1/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
<h1 class="d-flex justify-content-center">NEW</h1>
<form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">Title:</label>
    <input type="text" name="title" id="title" /> <br />
    <label for="content">Content:</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit" value="제출">
  </form>

  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}

django/23.03.20/day1_problem1/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous" />
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>